---
- name: Preconfig
  hosts: homework
  tasks:
    - name: Docker install
      block:
        - name: Add universe
          apt_repository:
            repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
            state: present
        - name: Packages install
          apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            update-cache: yes
            cache_valid_time: 86400 
        - name: Download Docker repo key
          get_url:
            url: https://download.docker.com/linux/ubuntu/gpg
            dest: /etc/apt/keyrings/docker.asc    
        - name: Set permissions on Docker repo key
          file:
            path: /etc/apt/keyrings/docker.asc
            mode: "0644"
        - name: Add Docker repo
          apt_repository:
            repo: >
              deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
            state: present
            update-cache: yes
            filename: docker
        - name: Docker-ce install
          apt:
            name: 
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            update-cache: yes
        - name: Check install and reload
          service:
            name: docker
            state: restarted
            enabled: yes    
    - name: Docker-compose install
      block:
        - name: Get latest varsion docker-compose
          uri:
            url: https://api.github.com/repos/docker/compose/releases/latest
            body_format: json     
          register: page
        - name: Docker-compose install
          get_url: 
            url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-Linux-x86_64" 
            dest: /usr/local/bin/docker-compose
            mode: 0755    
    - name: Compliting install
      block:
        - name: Add user in group docker
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
        - name: Reboot server
          reboot:       